# Generated by Django 5.1.1 on 2024-11-01 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0004_alter_vendor_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount for percentage type coupons', max_digits=8, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='minimum order value to apply the coupon', max_digits=10, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='maximun no of times this coupon can be used by all the users', null=True)),
                ('user_limit', models.PositiveIntegerField(blank=True, help_text='maximum no of times each user can use this coupon', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='optional description for the coupon')),
                ('vendor', models.ManyToManyField(blank=True, help_text='If specified the coupon is valid only for these vendors', null=True, to='vendor.vendor')),
            ],
        ),
    ]
