# Generated by Django 5.1.1 on 2024-11-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons_offers', '0001_initial'),
        ('vendor', '0004_alter_vendor_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='vendor',
            field=models.ManyToManyField(blank=True, help_text='If specified the coupon is valid only for these vendors', to='vendor.vendor'),
        ),
    ]
