# Generated by Django 5.1.1 on 2024-11-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons_offers', '0002_alter_coupons_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'verbose_name_plural': 'Coupons'},
        ),
    ]
