# Generated by Django 5.1.1 on 2024-10-28 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderedfood_fooditem'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorreview',
            unique_together={('user', 'order')},
        ),
        migrations.RemoveField(
            model_name='vendorreview',
            name='vendor',
        ),
    ]
