# Generated by Django 5.1.1 on 2024-10-28 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderedfood_fooditem'),
        ('reviews', '0002_alter_vendorreview_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorreview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vendorreview',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_review', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='vendorreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
