# Generated by Django 5.1.1 on 2024-10-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
