# Generated by Django 5.1.1 on 2024-10-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_fooditem_image_alter_fooditem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
