# Generated by Django 5.1.1 on 2024-10-07 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_fooditem_is_available'),
        ('vendor', '0004_alter_vendor_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
