# Generated by Django 5.1.1 on 2024-10-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_vendor'),
        ('vendor', '0004_alter_vendor_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category_name', 'vendor')},
        ),
    ]
