# Generated by Django 5.1.1 on 2024-10-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Razorpay', 'Razorpay'), ('COD', 'COD')], max_length=25),
        ),
    ]
