# Generated by Django 5.1.1 on 2024-10-27 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_category_category_name_and_more'),
        ('orders', '0004_remove_order_vendors_order_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfood',
            name='fooditem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.fooditem'),
        ),
    ]
