# Generated by Django 5.1.1 on 2024-11-07 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderedfood_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_foods', to='orders.order'),
        ),
    ]
